jobs:
  build-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Download Repo
        uses: actions/checkout@v4

      - name: Prepara S.O para Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION}}

      - name: Ajuste path e Adiciona Files
        run: | 
          pwd && ls -alh 
          cd mini-curso-devops
          cat << EOF >> vite.config.js
          import { defineConfig } from 'vite'
          // https://vitejs.dev/config/
          export default defineConfig({
          // Adicione esta linha:
          base: '/mini-curso-devops/', 
          } )
          EOF
          ls -alh
      - name: Instala dependencias e Build
        run: |
          pwd && ls -alh  
          cd mcd-ec2         
          npm install
          npm run build
      - name: Fazer o Upload do codigo
        uses: actions/upload-artifact@v4
        with: 
          name: dist-files
          path: mini-curso-devops/dist


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download do Arquivos 
        uses: actions/download-artifact@v4
        with: 
          name: dist-files
          path: dist
      - name: Enviar arquivos para Server 
        run: | 
          ls -alh 
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY_PROD }}" > ~/.ssh/key-prod.pem
          chmod 600 ~/.ssh/key-prod.pem
          scp -i ~/.ssh/key-prod.pem  -o StrictHostKeyChecking=no -r dist/* ubuntu@ec2.compute-1.amazonaws.com:/var/www/html/mini-curso-devops
          




env:
  AWS_REGION: 'us-east-1'
  S3_NAME: "mini-curso-devops"
  S3_PREFIX: "/"
  AWS_WEB_IDENTITY_TOKEN_FILE: "/tmp/gitlab_token"


jobs: 
  build:  
    runs-on: ubuntu-latest
    steps:
      - name: Download Repo
        uses: actions/checkout@v4 

      - name: Prepara S.O para Node
        uses: actions/setup-node@v4
        with: 
          node-version: 20




  deploy-s3: 
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write      
      contents: read    
    steps:
      - name: Download do Arquivos 
        uses: actions/download-artifact@v4
        with: 
          name: dist-files
          path: dist 

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
             
      - name: Copia de arquivos para S3 e faz o SYNC
        run: |
          set -e 
          aws s3 sync mini-curso-devops/dist s3://$S3_NAME/ --delete --region $AWS_REGION